name: API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: docker compose build api-prediction

      - name: Lancer la suite de tests
        run: docker compose run --rm api-prediction pytest
